name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Exécuter l'action quand un tag "vX.X.X" est poussé

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Installer les dépendances
        run: pip install build twine

      - name: Construire le package
        run: python -m build

      - name: Publier sur PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
